-- MySQL Script generated by MySQL Workbench
-- Fri Jun 19 12:09:41 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `colour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colour` (
  `idcolour` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idcolour`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `soort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `soort` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(450) NOT NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `t-shirt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `t-shirt` (
  `idT-shirt` INT NOT NULL AUTO_INCREMENT,
  `text_line_1` VARCHAR(2000) NOT NULL,
  `text_line_2` VARCHAR(2000) NOT NULL,
  `image_path` VARCHAR(250) NOT NULL,
  `colour_idcolour` INT NOT NULL,
  `soort_idtable1` INT NOT NULL,
  PRIMARY KEY (`idT-shirt`, `colour_idcolour`, `soort_idtable1`),
  INDEX `fk_t-shirt_colour_idx` (`colour_idcolour` ASC) VISIBLE,
  INDEX `fk_t-shirt_soort1_idx` (`soort_idtable1` ASC) VISIBLE,
  CONSTRAINT `fk_t-shirt_colour`
    FOREIGN KEY (`colour_idcolour`)
    REFERENCES `colour` (`idcolour`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t-shirt_soort1`
    FOREIGN KEY (`soort_idtable1`)
    REFERENCES `soort` (`idtable1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
